---
# Source: mushop/charts/payment/templates/payment-svc.yaml
apiVersion: v1
kind: Service
metadata:
  # TODO: update to payment.fullname when orders can receive variable
  name: payment
  labels: 
    app.kubernetes.io/name: payment
    helm.sh/chart: payment-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: payment
    app.kubernetes.io/instance: mushop
  ports:
    - port: 80
      name: http
      targetPort: 8080
