---
# Source: mushop/charts/storefront/templates/storefront-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mushop-storefront
  labels:
    app.kubernetes.io/name: storefront
    helm.sh/chart: storefront-0.2.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: storefront
    app.kubernetes.io/instance: mushop
  ports:
    - port: 80
      name: http
      targetPort: 8080
