---
# Source: mushop/charts/user/templates/user-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mushop-user
  labels: 
    app.kubernetes.io/name: user
    helm.sh/chart: user-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: user
    app.kubernetes.io/instance: mushop
  ports:
    - port: 80
      name: http
      targetPort: 3000
