---
# Source: mushop/charts/carts/templates/carts-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mushop-carts
  labels:
    app.kubernetes.io/name: carts
    helm.sh/chart: carts-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: carts
    app.kubernetes.io/instance: mushop
  ports:
    - port: 80
      name: http
      targetPort: 80
