---
# Source: mushop/charts/edge/templates/edge-hpa.yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mushop-edge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mushop-edge
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
