---
# Source: mushop/charts/edge/templates/edge-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mushop-edge
  labels:
    app.kubernetes.io/name: edge
    helm.sh/chart: edge-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge
      app.kubernetes.io/name: edge
      app.kubernetes.io/instance: mushop
  template:
    metadata:
      labels:
        app: edge
        version: "1.1.0"
        app.kubernetes.io/name: edge
        app.kubernetes.io/instance: mushop
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: edge
          image: "iad.ocir.io/oracle/ateam/mushop-edge-router:1.1.0"
          imagePullPolicy: IfNotPresent
          args:
          - --configfile=/config/traefik.toml
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /config
              name: config
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          #securityContext:
          #  capabilities:
          #    add:
          #    - NET_BIND_SERVICE
          #    drop:
          #    - all
          #  readOnlyRootFilesystem: true
          #  runAsNonRoot: true
          #  runAsUser: 10001
      volumes:
        - name: config
          configMap:
            name: mushop-edge
