---
# Source: mushop/charts/edge/templates/edge-svc.yaml
apiVersion: v1
kind: Service
metadata:
  # intentionally w/o .Release.Name for metrics workshop
  name: edge
  labels:
    app.kubernetes.io/name: edge
    helm.sh/chart: edge-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: edge
    app.kubernetes.io/instance: mushop
  ports:
    - port: 80
      name: http
      targetPort: 8080
