---
# Source: mushop/charts/assets/templates/assets-hpa.yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mushop-assets
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mushop-assets
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
