---
# Source: mushop/charts/assets/templates/deploy-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: mushop-assets-deploy-1
  labels: 
    app.kubernetes.io/name: assets
    helm.sh/chart: assets-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: assets
        app.kubernetes.io/instance: mushop
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: "iad.ocir.io/oracle/ateam/mushop-assets:1.1.3"
          imagePullPolicy: IfNotPresent
          command: ["node", "deploy.js"]
          env:
            
            - name: BUCKET_PAR
              valueFrom:
                secretKeyRef:
                  name: mushop-bucket
                  key: parUrl
                  optional: true
