---
# Source: mushop/charts/events/templates/events-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mushop-events
  labels:
    app.kubernetes.io/name: events
    helm.sh/chart: events-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
      app.kubernetes.io/name: events
      app.kubernetes.io/instance: mushop
  template:
    metadata:
      labels:
        app: events
        version: "0.0.2"
        app.kubernetes.io/name: events
        app.kubernetes.io/instance: mushop
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: events
          image: "iad.ocir.io/oracle/ateam/mushop-events:0.0.2"
          imagePullPolicy: IfNotPresent
          command: ["/app"]
          args:
          - -port=8080
          env:
            
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            periodSeconds: 120
            httpGet:
              path: /health
              port: http
          readinessProbe:
            periodSeconds: 10
            httpGet:
              path: /health
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          #securityContext:
          #  capabilities:
          #    add:
          #    - NET_BIND_SERVICE
          #    drop:
          #    - all
          #  readOnlyRootFilesystem: true
          #  runAsNonRoot: true
          #  runAsUser: 10001
