---
# Source: mushop/charts/api/templates/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mushop-api
  labels:
    app.kubernetes.io/name: api
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: mushop
  template:
    metadata:
      labels:
        app: api
        version: "2.3.2"
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: mushop
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: api
          image: "iad.ocir.io/oracle/ateam/mushop-api:2.3.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
          - name: MOCK_MODE
            value: "all"
          - name: SESSION_REDIS
            value: mushop-session
          - name: CATALOGUE_URL
            value: http://mushop-catalogue
          - name: ORDERS_URL
            value: http://mushop-orders
          - name: CARTS_URL
            value: http://mushop-carts
          - name: USERS_URL
            value: http://mushop-user
          - name: EVENTS_URL
            value: http://mushop-events
          - name: STATIC_MEDIA_URL
            value: /assets
          - name: NEWSLETTER_SUBSCRIBE_URL
            value: ""
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
          #securityContext:
          #  capabilities:
          #    add:
          #    - NET_BIND_SERVICE
          #    drop:
          #    - all
          #  readOnlyRootFilesystem: true
          #  runAsNonRoot: true
          #  runAsUser: 10001
