---
# Source: mushop/charts/session/templates/session-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mushop-session
  labels:
    app.kubernetes.io/name: session
    helm.sh/chart: session-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: session
    app.kubernetes.io/instance: mushop
  ports:
    - port: 6379
      name: redis
