---
# Source: mushop/charts/catalogue/templates/catalogue-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mushop-catalogue
  labels:
    app.kubernetes.io/name: catalogue
    helm.sh/chart: catalogue-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: catalogue
    app.kubernetes.io/instance: mushop
  ports:
    - port: 80
      name: http
      targetPort: 8080
