---
# Source: mushop/charts/catalogue/templates/catalogue-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mushop-catalogue
  labels: 
    app.kubernetes.io/name: catalogue
    helm.sh/chart: catalogue-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      app.kubernetes.io/name: catalogue
      app.kubernetes.io/instance: mushop
  template:
    metadata:
      labels:
        app: catalogue
        version: "1.4"
        app.kubernetes.io/name: catalogue
        app.kubernetes.io/instance: mushop
        mockmode: "all"
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      terminationGracePeriodSeconds: 5
      #initContainers:
        
      containers:
        - name: catalogue
          image: "iad.ocir.io/oracle/ateam/mushop-catalogue:1.4"
          imagePullPolicy: Always
          command: ["/app/catalogue"]
          args:
          - -port=8080
          ports:
            - name: http-alt
              containerPort: 8080
          env:
            - name: ZIPKIN
              value: 
            - name: OADB_USER
              valueFrom:
                secretKeyRef:
                  name: catalogue-oadb-credentials
                  key: oadb_user
            - name: OADB_PW
              valueFrom:
                secretKeyRef:
                  name: catalogue-oadb-credentials
                  key: oadb_pw
            - name: OADB_SERVICE
              valueFrom:
                secretKeyRef:
                  name: catalogue-oadb-connection
                  key: oadb_service
          volumeMounts:
            - name: wallet
              mountPath: /usr/lib/oracle/19.10/client64/lib/network/admin/
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: http-alt
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http-alt
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          #securityContext:
          #  capabilities:
          #    add:
          #    - NET_BIND_SERVICE
          #    drop:
          #    - all
          #  readOnlyRootFilesystem: true
      volumes:
        
        # local wallet
        - name: wallet
          secret:
            secretName: catalogue-oadb-wallet
            #defaultMode: 256
        # service init configMap
        - name: initdb
          configMap:
            name: mushop-catalogue-init
            items:
            - key: atp.init.sql
              path: service.sql
      #securityContext:
      #  fsGroup: 687467
